# GLOBAL SITE SETTINGS

cname: liquidvisual.yourwebvisual.com

# META
title: liquidvisual
seo_title:
company: liquidvisual
description:

# SITE DEFAULTS
site_tagline:

# DEVELOPER
allow_robots: false
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/________
github_repo_name:
jekyll_version: 3.5.0

# OFFICES
offices:
  - title:
    address:

# SOCIAL MEDIA
social_media:
  - title: Codepen
    url: https://codepen.io/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-codepen

  - title: Dribbble
    url: https://dribbble.com/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-dribbble

  - title: Facebook
    url: https://facebook.com/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-facebook
    exclude: true

  - title: Github
    url: https://github.com/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-github

  - title: Instagram
    url: https://www.instagram.com/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-instagram

  - title: Pinterest
    url: https://pinterest.com/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-pinterest
    exclude: true

  - title: Slack
    url:
    alias: '@liquidvisual'
    icon: fa fa-slack
    exclude: true

  - title: Trello
    url: https://trello.com/liquidvisual
    alias: '@liquidv'
    icon: fa fa-trello

  - title: YouTube
    url: https://youtube.com/liquidv
    alias: '@liquidv'
    icon: fa fa-youtube-play

# GOOGLE
google_analytics: "UA-XXXXXXXX-X"

# AUTHOR
author:
  title: Mitch
  url: http://liquidvisual.com
  logo: /assets/img/ui/liquidvisual-logo.svg
  description: liquidvisual