# GLOBAL SITE SETTINGS
cname: liquidvisual.yourwebvisual.com
allow_robots: false

# META
title: liquidvisual
title_homepage: Freelance Web Developer in Sydney | Mitch Warren
# title_homepage: liquidvisual | Freelance Web Developer + Design in Sydney
company: liquidvisual Web Development Sydney
description: Mitch is a Sydney based freelance front-end web designer who specialises in custom website builds for digital agencies in Australia.

# DEVELOPER
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/liquidvisual-2017
github_repo_name: liquidvisual-2017
jekyll_version: 3.7.0

# OFFICES
offices:
  - title:
    address:

# SOCIAL MEDIA
social_media:
  - title: Codepen
    url: https://codepen.io/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-codepen
    exclude: true

  - title: Dribbble
    url: https://dribbble.com/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-dribbble

  - title: Facebook
    url: https://facebook.com/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-facebook
    exclude: true

  - title: Github
    url: https://github.com/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-github

  - title: Instagram
    url: https://www.instagram.com/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-instagram

  - title: Pinterest
    url: https://pinterest.com/liquidvisual
    alias: '@liquidvisual'
    icon: fa fa-pinterest
    exclude: true

  - title: Slack
    url:
    alias: '@liquidvisual'
    icon: fa fa-slack
    exclude: true

  - title: Trello
    url: https://trello.com/liquidvisual
    alias: '@liquidv'
    icon: fa fa-trello
    exclude: true

  - title: Twitter
    url: https://twitter.com/WriteMitch
    alias: '@WriteMitch'
    icon: fa fa-twitter

  - title: YouTube
    url: https://www.youtube.com/channel/UC4S74VhUhaL1HGv3kxYyH6Q
    alias: '@danandmitch'
    icon: fa fa-youtube-play
    # exclude: true

# GOOGLE
google_analytics: 'UA-26850234-1'

# AUTHOR
author:
  title: Mitch
  url: http://liquidvisual.com
  logo: /assets/img/ui/liquidvisual-logo.svg
  description: by liquidvisual